services:
  web:
    build: .
    ports:
      - "8111:8111"
    volumes:
      - ./app:/code/app   # dev: mount source so --reload sees changes
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8111
